import type { Metadata } from "next";
import { Tinos } from "next/font/google";
import "./globals.css";
import SharedNavbar from "@/components/shared/navbar";
import SharedFooter from "@/components/shared/footer";

const tinos = Tinos({
  weight: "400",
});

export const metadata: Metadata = {
  title: "Article",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${tinos.className} antialiased`}>{children}</body>
    </html>
  );
}
